<?php
$limit = Mage::getStoreConfig('pp_section_setttings/crosssell/cross_sell_page_items');
$collection = $this->getCrossSellingItemsByOrderId($this->getData('orderId'), $limit);
$count = count($collection);
?>
<?php if($count): ?>
    <div class="pptrack-crosssell">
        <h2><?php echo Mage::helper('pptrack')->__('While waiting, we have something for you. Check offerings bellow:') ?></h2>
        <ul class="pptrack-products-grid pptrack-products-grid--col-<?php echo $count ?>">
            <?php foreach ($collection as $_item): ?>
                <li>
                    <div class="pptrack-list-info-box-wrap">
                        <div class="pptrack-list-info-box">
                            <a class="pptrack-product-image" href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_item->getName()) ?>">
                                <img src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(null, 150); ?>" alt="<?php echo $this->escapeHtml($_item->getName()) ?>" />
                            </a>
                            <h3 class="pptrack-product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->escapeHtml($_item->getName()) ?></a></h3>
                            <?php echo $this->getPriceHtml($_item, true) ?>
                        </div>
                    </div>
                    <button type="button" title="<?php echo Mage::helper('pptrack')->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_item) ?>')"><span><span><?php echo Mage::helper('pptrack')->__('Add to Cart') ?></span></span></button>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <script type="text/javascript">
        function fixCrossBoxes() {
            var max = 0;
            $$(".pptrack-list-info-box").forEach(function (el) {
                max = Math.max(max, el.getHeight());
            });
            $$(".pptrack-list-info-box-wrap").forEach(function (el) {
                el.setStyle({
                    height: max + 'px'
                });
            });
        }
        window.onresize = function(event) {
            fixCrossBoxes();
        };

        Event.observe(window, "load", function() {
            fixCrossBoxes();

        }, false);

    </script>
<?php endif; ?>
