<?php
$category = Mage::getSingleton('catalog/layer')->getCurrentCategory();
$categories = $category->getCollection()
    ->addAttributeToSelect(array('name', 'thumbnail'))
    ->addAttributeToFilter('is_active', 1)
    ->addIdFilter($category->getChildren())
?>
<div class="subcategories">
    <p>Select a category to view products:</p>
    <ul class="clearfix">
        <!-- Display Each Subcategory Image and Name  -->

        <?php foreach ($categories as $category): ?>
            <li class="grid12-3">
                <a href="<?php echo $category->getUrl() ?>" class="clearfix">
                    <?php if ($thumbFile = $category->getThumbnail()): ?>
                        <img
                            src="<?php echo Mage::getBaseUrl('media') . 'catalog' . DS . 'category' . DS . $thumbFile; ?>"
                            alt="<?php echo $this->htmlEscape($category->getName()) ?>"/>
                    <?php endif; ?>
                    <span><?php echo $category->getName() ?></span></a>
            </li>
            <!-- Load (3) Products from within each subcategory  -->
            <?php
            $_helper = $this->helper('catalog/output');
            $products = Mage::getModel('catalog/product')
                ->getCollection()
                ->addCategoryFilter($category)
                ->addAttributeToSelect(array('name', 'product_url', 'small_image'))
                ->load();
            ?>
            <div class="widget widget-new-products">
                <div class="widget-title">
                    <h2><?php echo $this->__('New Products') ?></h2>
                </div>
                <div class="widget-products">
                    <?php echo $this->getPagerHtml() ?>

                    <!-- Display Each product's detailed info  -->
                    <?php foreach ($products as $product): ?>
                        <li>
                            <div class="row float">
                                <div class="list-group category-products float">


                                    <div class="product-img-box">
                                        <?php // Product Image ?>
                                        <a href="<?php echo $product->getProductUrl() ?>"
                                           title="<?php echo $this->stripTags($this->getImageLabel($product, 'small_image'), null, true) ?>"
                                           class="product-image"><img
                                                src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(135); ?>"
                                                width="135" height="135"
                                                alt="<?php echo $this->stripTags($this->getImageLabel($product, 'small_image'), null, true) ?>"/></a>
                                        <?php // Product description ?>
                                        <div class="lightborder">

                                            <div class="row pricerow">
                                                <div class="col-lg-8">
                                                    <h3 class="list-group-item-heading product-description"><a
                                                            href="<?php echo $product->getProductUrl() ?>"
                                                            title="<?php echo $this->stripTags($product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($product, $product->getName(), 'name') ?></a>
                                                    </h3>
                                                </div>
                                                <div class="col-lg-4">
                                                    <div class="product-price"><?php echo $this->getPriceHtml($product, true, '-widget-new-list') ?></div>
                                                </div>
                                            </div>


                                            <p class="list-group-item-text " >

                                            <div class="row swatchesrow" >
                                                <div class="swatches" >
                                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                                                        <a href="#" class="thumbnail box-border Hpadding ">
                                                            <img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(70) ?>" width="90" height="100" alt="<?php echo $this->stripTags($product->getName(), null, true) ?>" />
                                                        </a>
                                                    </div>
                                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                                                        <a href="<?php echo $product->getProductUrl() ?>" class="thumbnail box-border Hpadding">
                                                            <img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(70) ?>" width="90" height="100" alt="<?php echo $this->stripTags($product->getName(), null, true) ?>" />
                                                        </a>
                                                    </div>
                                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                                                        <a href="#" class="thumbnail box-border Hpadding">
                                                            <img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(70) ?>" width="90" height="100" alt="<?php echo $this->stripTags($product->getName(), null, true) ?>" />
                                                        </a>
                                                    </div>
                                                </div>

                                            </div>
                                            <div class="row product-owner">
                                                <div class="col-lg-2 product-category-profile">

                                                </div>
                                                <div class="col-lg-7">

                                                </div>
                                                <div class="col-lg-3">

                                                </div>
                                            </div>

                                            </p>
                                            </div>

                        </li>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php endforeach; ?>
    </ul>
</div>